### ISSUE TITLE
Feat: post-page 기능 구현

### ISSUE THREAD

**Issue by Februaar** [inssagram/FE#104]
## Description

게시글 페이지에 적용된 기능 구현

## To-Do

- [x] Ellipsis Modal,  AccountInfo Modal 띄우기(링크 복사, 계정 정보 확인 가능)
- [x] 게시글 링크 복사 기능
- [x] 계정 정보 연결
- [x] 팔로우, 좋아요, 저장하기 버튼 css
- [x] 팔로우, 좋아요, 저장하기 버튼 상태관리 get, post 테스트 완료
- [x] 게시글 페이지에서 다이렉트 페이지 라우터 설정

## ETC

좋아요, 저장하기 버튼 리덕스로 어떻게 관리할지 고민 중
기존 인스타그램에선 다이렉트 아이콘 누르면 해당 게시글을 다른 사람과 공유하는 방향으로 되어있는데 우선 해당 계정과의 다이렉트 페이지와 라우터 설정을 해둔 상태입니다.. 이것도 회의 해봐욥

**Comment by joshyeom** [comment]
좋아요랑 저장하기 버튼 서버로 요청보내서 해결하면 되지않을까요?? 리덕스로 괜히 열심히 만들었는데 백에서 해결되면 씁쓸하니까...

**Comment by Februaar** [comment]
> 좋아요랑 저장하기 버튼 서버로 요청보내서 해결하면 되지않을까요?? 리덕스로 괜히 열심히 만들었는데 백에서 해결되면 씁쓸하니까...

그 생각을 제일 먼저 하긴했는데 이 파트 아니면 리덕스를 사용해볼 일이 없을 것 같아서 고민이에여....

**Comment by joshyeom** [comment]
> > 좋아요랑 저장하기 버튼 서버로 요청보내서 해결하면 되지않을까요?? 리덕스로 괜히 열심히 만들었는데 백에서 해결되면 씁쓸하니까...
> 
> 그 생각을 제일 먼저 하긴했는데 이 파트 아니면 리덕스를 사용해볼 일이 없을 것 같아서 고민이에여....

공부목적이면 시도해보고 구현목적이면 잠깐 보류해보시져

**Comment by oinochoe** [comment]
좋아요랑 저장하기 버튼은 보통 현업에서는 실시간 API 반영으로 관리되기는 하는데, 혹시 요즘 다른 사람들에게도 실시간 보여주는 기능들을 하고 싶으면 Socket통신을 해봐도 되지 않을까 싶습니다. 😄

**Comment by Daily-manjoo** [comment]
아...........나는 정보 연결 이런게 너무 어렵더라...........

**Comment by Februaar** [comment]
> 좋아요랑 저장하기 버튼은 보통 현업에서는 실시간 API 반영으로 관리되기는 하는데, 혹시 요즘 다른 사람들에게도 실시간 보여주는 기능들을 하고 싶으면 Socket통신을 해봐도 되지 않을까 싶습니다. 😄

생각만 해도 살짝 올라올 것 같습니다...제가 감히 해낼 수 있을까요ㅎㅎ
