### ISSUE TITLE
Refactor: Story page

### ISSUE THREAD

**Issue by joshyeom** [inssagram/FE#105]
## Description
Story 페이지 캐러샐로 구현해서 새로운 사진 무한 스크롤로 수정하고 버그 및 리팩토링

## To-Do
- [x] story 데이터 생성
- [x] story 데이터 연동
- [x] 현 이용자 게시물은 애니메이션 없이 변환
- [x] 타 이용자로 넘어갈 때 케러샐
- [x] 이벤트 전파 버그
- [x] DM 보내기
- [x] 캐러셀 넘어갈때 이미지 보존
