### ISSUE TITLE
Feat: Story 작성 페이지 기능 구현

### ISSUE THREAD

**Issue by joshyeom** [inssagram/FE#141]
## Description
작성페이지 레이아웃은 되어있는데, 기능 구현이 안되어있어서 진행해보려고 합니다. 코멘트 부분을 마우스로 드래그 할 수 있게 하고, 가능하면 크기 조절 및 방향전환까지 해보려고 합니다. 모두 구현되고 사진으로 저장하여 보내보려고 합니다.

## To-Do
- [x] 코멘트 박스 생성
- [x] 코멘트 박스 드래그, 크기 조절
- [x] 저장된 이미지 post요청
- [x] 저장된 이미지 미리보기
