### ISSUE TITLE
Refactor: 게시글 POST 파이어베이스 연동 및 최적화

### ISSUE THREAD

**Issue by joshyeom** [inssagram/FE#154]
## Description
게시글도 이미지를 올려야 하는데, 파이어베이스에 올리고 이미지를 압축하는 과정을 할겁니다. 
이를 통해 더 빠른 렌더링이 가능하지요! 그러므로 게시글 POST를 조금 손대보겠습니다.

## To-Do
- [x] 게시글 이미지 파이어베이스 저장 및 서버 업로드
- [x] 이미지 리사이징
- [x] 리사이징 전 후 시간 체크
- [x] 업로드 중 중복 업로드 방지
