### ISSUE TITLE
Refactor: 마이페이지 & 유저페이지

### ISSUE THREAD

**Issue by Februaar** [inssagram/FE#180]
## Description

마이페이지와 유저페이지 구분 된 리팩 진행 사항입니다

## To-Do
- [X] 마이페이지/유저페이지 직업 표시
- [x] 마이페이지 직업 데이터가 없을 경우 프로필 수정으로 라우터 설정
- [x] 네비게이션 바 라우터 버벅거림 오류 해결(좋아요 누른 게시글, 북마크한 게시글 라우팅)
