### ISSUE TITLE
Refactor: 알림페이지

### ISSUE THREAD

**Issue by Februaar** [inssagram/FE#181]
## Description

알림페이지 리팩 진행 사항입니다

## To-Do
- [x] Header와 Footer에 SSE 연결하기
- [x] 팔로우 알림과 게시글 관련 알림 구분해서 UI 띄우기
- [x] 채팅 알림이 왔을 때 보여주는 UI 생성
- [x] 알림 삭제하기 버튼
- [x] 알림 모두 삭제하기 버튼
