### ISSUE TITLE
Refactor: 검색페이지

### ISSUE THREAD

**Issue by Februaar** [inssagram/FE#182]
## Description

검색페이지 리팩 진행 사항입니다

## To-Do
- [x] 검색 기록에 friendStatus 반영
- [x] 검색 기록 저장하기 post 요청 확인
- [x] 최근 검색 기록에 있을 때 다시 저장하기 post 요청시 500 에러 확인
- [x] 검색 기록 /user 페이지로 라우팅 설정
- [x] 최근 검색 기록 get 요청 확인
