### ISSUE TITLE
Feat: 게시글 페이지 레이아웃

### ISSUE THREAD

**Issue by Daily-manjoo** [inssagram/FE#40]
## Description

게시글 페이지 레이아웃 할 거임

## To-Do

- [x] 게시글 조회 페이지
- [x] 게시글 수정 페이지
- [x] 게시글 댓글 페이지

## ETC
조회는 정호님 걸로 가져와야겠다~
