### ISSUE TITLE
Feature: explore page > search page 검색 기능 테스트

### ISSUE THREAD

**Issue by Februaar** [inssagram/FE#63]
## Description

- 검색바에 입력 값을 감지했을 때 search page로 라우팅 기능
- 검색 관련 기능 구현

## To-Do
- [x] 계정 검색 자동완성 기능(account.json)
- [x] 검색 결과 리스트 렌더링 테스트
- [x] SearchBar 컴포넌트 by situation layout 수정

## ETC
또 밤을 새워버렸습니다. 죄송합니다. 잘자요~~
