### ISSUE TITLE
Feat: direct-new-page 새로운 채팅방 만들기

### ISSUE THREAD

**Issue by Februaar** [inssagram/FE#82]
## Description

새로운 계정으로 새로운 채팅방 만들기

## To-Do

- [x] 검색한 계정 리스트로 렌더링 테스트
- [x] 선택한 계정 input에 태그로 표시
- [x] 선택한 계정으로 새로운 채팅방 연결

## ETC

빨리 api 연결하고 싶다.... 백엔드 보고있나요
갈수록 어려워지는 중임에도 다들 화이팅!!
